name: publish packages

on:
  release:
    types: [ created ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Env
      - name: Set environment variables
        run: |
            echo "DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true" >> $GITHUB_ENV
            echo "DOTNET_CLI_TELEMETRY_OPTOUT=true" >> $GITHUB_ENV
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      # Prep
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: '5.0.x'
        
      # Build          
      - name: Restore
        run: dotnet restore
               
      - name: Pack
        run: dotnet pack -c Release --no-restore -o nupkg /p:Version=${{ env.RELEASE_VERSION }}
      
      # Push
      - name: Push generated package to GitHub registry
        run: dotnet nuget push './nupkg/*.nupkg' -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{ secrets.NUGET_API_KEY }}
