name: publish packages

on:
  release:
    types: [ created ]

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Prep
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: '3.1.x'

      - name: Add Private Nuget Feed
        run: Out-File -FilePath "nuget.config" -InputObject "<?xml version=`"1.0`" encoding=`"utf-8`"?>
         <configuration>
               <packageSources>
                    <clear />
                    <add key=`"github`" value=`"https://nuget.pkg.github.com/assureddt/index.json`" />
                    <add key=`"nuget`" value=`"https://api.nuget.org/v3/index.json`" />
                </packageSources>
                <packageSourceCredentials>
                    <github>
                        <add key=`"Username`" value=`"assureddt`" />
                        <add key=`"ClearTextPassword`" value=`"${{ secrets.GITHUB_TOKEN }}`" />
                    </github>
                </packageSourceCredentials>
         </configuration>"
        shell: pwsh
        
      # Build
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c Release --no-restore
      
      - name: Pack
        run: dotnet pack -c Release --no-restore --include-symbols --include-source -o nupkg
      
      # Push
      - name: Push generated package to GitHub registry
        run: dotnet nuget push './nupkg/*.nupkg' -s github --skip-duplicate
